- .github/workflows/ci.yml
We add in the `workflow` that the tests are run when a PR is created. This allows us to corroborate that the tests pass correctly when we want to upload the changes.
Update `workflow`
> add tests in workflow

- .github/workflows/ci.yml
> Fix workflow indentation

- cypress/tests/ui/homepage.spec.ts
- package-lock.json
- package.json
- src/common/components/Input/ContractInput.tsx
- src/common/components/Input/FunctionParameter.tsx
- src/common/components/Tabs/FunctionsTab/FunctionsTab.tsx
- src/common/hooks/useInvocation.ts
- src/pages/home/Home.tsx
- src/providers/InvocationProvider.tsx
- tailwind.config.js
- This will allow an easy implementation of the invocation edition
- Added `react-hook-form` to the project's dependencies
- Updated the `ContractInput.tsx` component to accept and handle a new loadContract function.
- Introduced a new component `FunctionParameter.tsx` to manage function parameters
- Introduced a new component `FunctionsTab.tsx` which allows users to select and manage functions related to contract invocations.
- Added a new hook `useInvocation.ts` which provides a context for managing invocations.
- Made changes in `Home.tsx` to incorporate the new components and logic for a better user experience.
- Introduced an `InvocationProvider` which provides a context for managing invocations throughout the application.
> Implement functions tab

- .prettierrc
- cypress/support/commands.ts
- package-lock.json
- package.json
- src/common/api/collections.ts
- src/common/components/Loader/AppLoader.tsx
- src/common/components/auth/CreateAccount.tsx
- src/common/hooks/useAxios.ts
- src/providers/AuthProvider.tsx
- src/services/auth/hook/useAuth.tsx
- We want to have a proper base to be able to make authorised requests
- Add react-query to handle queries and mutations
- Add new `useAxios` hook to automatically add the authorization header to the requests
- Implement register flow using our backend
> Intercept requests and implement backend register

- package-lock.json
- package.json
- src/common/api/collections.ts
- src/common/components/Collections/CollectionCard.tsx
- src/common/components/Collections/CollectionPlaceholder.tsx
- src/common/components/Collections/CollectionsEmptyState.tsx
- src/common/components/Collections/DeleteCollectionDialog.tsx
- src/common/components/Collections/EditCollectionDialog.tsx
- src/common/components/Collections/NewCollectionDialog.tsx
- src/common/components/ui/alert-dialog.tsx
- src/pages/home/Home.tsx
- We want to be able to edit and remove collections
- Implement collections remove and edit
- Add new collections empty state
> Edit and Remove collections

- src/common/api/invocations.ts
- src/common/components/Folders/Folder.tsx
- src/common/components/Folders/Folders.tsx
- src/common/components/Invocations/NewInvocationButton.tsx
- src/pages/collection/CollectionPage.tsx
- We want to implement a new collection page UI, this will be shown when no invocation is selected
-  Implement new collection page UI
> Implement new collection page UI

- cypress/tests/ui/authpage.spec.ts
- src/common/components/Input/ContractInput.tsx
- src/common/components/Tabs/AuthorizationTab/AuthorizationTab.tsx
- src/common/components/Tabs/FunctionsTab/FunctionsTab.tsx
- src/common/components/auth/ChangePassword.tsx
- src/common/components/auth/CreateAccount.tsx
- src/common/components/auth/Login.tsx
- src/common/components/sidebar/Sidebar.tsx
- src/pages/Invocation/InvocationPage.tsx
- There are some small UI problems that we need to solve
- Replace tesnet with futurenet
- Improve UI
> Small ui improvements. Replace testnet with futurenet.

- cypress.config.ts
- cypress/tests/ui/invocations.spec.ts
- src/common/api/folders.ts
- src/common/api/invocations.ts
- src/common/components/Folders/Folder.tsx
- src/common/components/Folders/Folders.tsx
- src/common/components/Invocations/InvocationListItem.tsx
- src/common/components/Invocations/NewInvocationButton.tsx
- We are not updating cache in some places of the app+
- Handle cache updates
- Add new queries
> Handle cache updates

- cypress/tests/ui/authpage.spec.ts
- cypress/tests/ui/sidebar.spec.ts
- src/common/components/Collections/CollectionCard.tsx
- src/common/components/Input/ContractInput.tsx
- src/common/components/Tabs/FunctionsTab/ParametersForm.tsx
- src/common/components/auth/ChangePassword.tsx
- src/common/components/auth/ResetPassword.tsx
- src/common/components/sidebar/Sidebar.tsx
- src/common/components/ui/Terminal.tsx
- src/pages/home/Home.tsx
- There are some small interactions that we want to improve.
- Add folders count to collection card
- Disable Run button while running invocation
- Scroll to bottom of the terminal when receiving a new response
> Small UX improvements

- cypress.config.ts
- cypress/tests/ui/authpage.spec.ts
- src/common/components/auth/CreateAccount.tsx
- src/common/components/auth/Login.tsx
- src/common/components/auth/RecoverPassword.tsx
- src/common/components/auth/ResetPassword.tsx
- src/common/components/auth/stellar/CreateNewAccount.tsx
- src/configs/router/index.tsx
- src/pages/auth/AuthPage.tsx
- src/pages/auth/ProtectedRoute.tsx
- There were some issues about how we handled auth routes. We want to introduce a specific route for them now so it's easier to handle. 
- Implement new `/auth/ route
- Update auth form styles
- Found generated account
> Implement new auth route

- package.json
- src/common/components/Tabs/AuthorizationTab/AuthorizationTab.tsx
- src/common/components/sidebar/Sidebar.tsx
- src/common/components/ui/Terminal.tsx
- src/common/components/ui/badge.tsx
- src/common/hooks/useAxios.ts
- src/pages/Invocation/InvocationPage.tsx
- src/pages/Invocation/useInvocation.ts
- Setting the authorization keys could be easily missed by the user, we want to show some visual hint for them to know that they are missing this required fields.
- Add Beta badge
- Show warning when missing invocation keys
- Improve errors in the terminal
- Update UI version to 1.0.0 🎉
> Beta badge & UI Improvements - Version 1.0.0 🎉

- package-lock.json
- src/common/components/Tabs/FunctionsTab/FunctionsTab.tsx
- Current empty state doesn't really tell the user what to do.
- Add CTA copy under the main title
> Improve invocation page empty state

- src/common/components/Collections/CollectionCard.tsx
- src/common/components/Input/SaveContractDialog.tsx
- src/pages/Invocation/useInvocation.tsx
- src/pages/home/Home.tsx
- There are some small changes we want to have in the UI.
- Handle unexpected error
- Improve collection card UI
- Improve update contract address warning copy
> Collection card UI improvements

- cypress/fixtures/folders/one-folder-length.json
- cypress/tests/ui/exceptions/contants.ts
- package-lock.json
- package.json
- src/common/api/invocations.ts
- src/common/components/Collections/CollectionCard.tsx
- src/common/components/PreInvocate/Editor.tsx
- src/common/components/PreInvocate/EditorHelpers.tsx
- src/common/components/Tabs/PreInvocateTab/PreInvocateTab.tsx
- src/common/constants/editor-helpers.ts
- src/common/constants/keizai.ts
- src/common/hooks/useEditor.ts
- src/common/types/invocation.ts
- src/pages/Invocation/InvocationPage.tsx
we added to use the new tab related to pre scripting, where the user can send code prior to the execution of the invocation
Create PreInvocatePage
Implement monaco editor
Add use-debounce and monaco editor to dependencies
Create hook useEditor
> Feature: Add pre invocation page

- src/common/api/invocations.ts
- src/common/components/ui/Terminal.tsx
- src/common/types/invocation.ts
- src/pages/Invocation/invocation.utils.tsx
- src/pages/Invocation/useInvocation.tsx
We modify the way in which we receive the response of the invoked invocation, since in the response from the back we also receive the preInvocation.
Create types to Invocation and PreInvocation
Create new component to the response from PreInvocation
Update response values
> Add pre invocation to response from run invocation method

- src/common/components/PreInvocate/EditorHelpers.tsx
- src/common/constants/editor/keizai.ts
- src/common/types/invocation.ts
- src/pages/Invocation/InvocationPage.tsx
- src/pages/Invocation/useInvocation.tsx
We added a method to be able to run the pre invocation.
We modify the response that we obtain at the moment of running the invocation.
We modify the name of the helper that we use to show the available methods in the editor.
Update invocation response
Update Keizai constant helper name
> Feature: Update invocation response & Update Keizai name Helper

- src/pages/Invocation/invocation.utils.tsx
- src/pages/Invocation/useInvocation.tsx
We added a response for the logic of running the pre-invocation.
We modify the response object of the pre invocation.
We no longer show the pre invocation response in case there is no response.
Update pre invocation method in useInvocation hook
Update component response of pre invocation
> Feature: Update pre invocation response

- src/common/api/enviroments.ts
Modify the endpoint from which we get the environment variables related to a collection
Update `environments` api service
> update endpoint to gets environments by collectionId

- .husky/pre-commit
- package.json
Remove tsc before to run build
> Chore/ remove tsc before build

- cypress/fixtures/environments/three-length-environments.json
- src/common/api/enviroments.ts
- src/common/constants/editor/keizai.ts
- src/pages/Invocation/preInvocation/keizai/keizai.service.ts
- src/pages/Invocation/useInvocation.tsx
- We are currently not waiting for the preinvocation script and this causes issues when running the invocation
- Add async to eval and snippets
> Implement await on preinvocation

- src/common/constants/editor-helpers.ts
- src/common/constants/editor/keizai.ts
- src/pages/Invocation/preInvocation/keizai/keizai.service.ts
We added a new method within the keizai service to obtain a collection variable by using the name
Update `keizai.service`
Update `editor helper`
> Feat:  Add new method in keizai service. add new editor helper

- cypress/tests/ui/environments.spec.ts
- src/common/api/enviroments.ts
- src/common/components/Collections/CollectionVariablesContainer.tsx
We add a conditional so that the variables are updated when any of the variables are modified.
> Feature: add refetch attribute on environments querie

- src/common/components/ui/Terminal.tsx
- src/pages/Invocation/invocation.utils.tsx
- src/pages/Invocation/useInvocation.tsx
We modify the answer we get in the terminal.
We add the post invocation response
We refactor a component for common use
> Feature: Refactor invocation response

- cypress/tests/ui/environments.spec.ts
- cypress/tests/ui/exceptions/constants.ts
- src/common/components/Collections/CollectionVariables.tsx
- src/common/components/Environments/EnvironmentDropdown.tsx
- src/common/components/Environments/EnvironmentEmptyState.tsx
- src/common/components/Environments/EnvironmentList.tsx
- src/common/exceptions/environments.ts
- Add empty state in environments
- Add empty state in `CollectionVariables` page and `EnvironmentsDropdown` components
> Feature: Add Environment empty state

- index.html
- src/common/components/FeedbackPopupButton/FeedbackPopupButton.tsx
- src/pages/Root.tsx
- We want a new way of reporting feedback and bugs
- Add feedback and bug report button. 
- Import tally in index.html
> Feedback form button

- cypress/fixtures/folders/folder-with-two-invocations.json
- cypress/fixtures/invocations/new-invocation.json
- cypress/tests/ui/exceptions/constants.ts
- cypress/tests/ui/invocations.spec.ts
- src/common/components/Tabs/EventsTab/EventEmptyState.tsx
- src/common/hooks/useContractEvents.ts
- src/pages/Invocation/InvocationPage.tsx
- src/pages/Invocation/useInvocation.tsx
- Fixed an error when setting events in the same state
- A custom hook is added to handle events
- Events are saved to `sessionStorage` using their `invocationId`
> Fix: Contract Events

- cypress/fixtures/invocations/invocation-with-env-contract.json
- cypress/tests/ui/environments.spec.ts
- src/common/components/Input/ContractInput.tsx
- src/common/components/Input/FunctionParameter.tsx
- src/common/components/Input/SaveContractDialog.tsx
- src/common/hooks/useEnvironments.ts
- Add edit contract address with environment variables
- Add environments in edit contract address
- Refactor `useEnvironments`
https://github.com/keizai-tools/keizai-ui/assets/60760903/d3892d8a-3a1f-47df-80bb-268f4d809bd5
> Feat: Add environments in edit contract address

- cypress/cypress.d.ts
- cypress/support/commands.ts
- src/common/components/Input/SelectNetwork.tsx
- src/common/components/auth/CreateAccount.tsx
- src/common/components/ui/alert-dialog.tsx
- src/common/components/ui/badge.tsx
- src/common/components/ui/button.tsx
- src/common/hooks/useAxios.ts
- src/pages/Invocation/InvocationPage.tsx
- src/providers/ThemeProvider.tsx
- The warnings that the application had been corrected.
Warnings are corrected to
- `shadcn/ui`
- linter
- `react-hook-form`
> Fix: Application warnings

- cypress/tests/ui/environments.spec.ts
- cypress/tests/ui/invocations.spec.ts
- package-lock.json
- package.json
- src/common/components/Environments/EnvironmentDropdown.tsx
- src/common/components/Environments/EnvironmentDropdownContainer.tsx
- src/common/components/Input/ContractInput.tsx
- src/common/components/Input/EnvironmentInput.tsx
- src/common/components/Input/FunctionParameter.tsx
- src/common/components/Input/SaveContractDialog.tsx
- Added the ability to color application variables when selecting them.
- Replace inputs in contract address, edit contract address, and param value by  an editor,
https://github.com/keizai-tools/keizai-ui/assets/60760903/23e63f42-90a0-46b1-b7fd-9530c4121bdf
> Feat: Colorize the variables

- src/common/components/Tabs/Editor/EditorTab.tsx
- src/common/components/Tabs/TabsContainer.tsx
- src/pages/Invocation/InvocationPage.tsx
- Fixed Monaco editor warning.
- Fixed a styling error in the Tabs list
- Added a click handle to `TabsContainer` to correct the background and text color when activated
> Fix: Editor warning and tabs styling

- src/common/components/FeedbackPopupButton/FeedbackPopupButton.tsx
- src/common/components/Input/SaveContractDialog.tsx
- src/common/components/ui/Terminal.tsx
- Two errors are corrected in the application layout
- Add z-index in feedback button
- Extend the width in the modal for editing a contract address
https://github.com/keizai-tools/keizai-ui/assets/60760903/5ebe6361-211d-478a-8cbd-a2fc10929fe5
> Fix modal width and feedback z-index

- cypress/fixtures/teams/all-teams.json
- cypress/tests/ui/auth/change-password.spec.ts
- cypress/tests/ui/collections.spec.ts
- cypress/tests/ui/environments.spec.ts
- cypress/tests/ui/exceptions/constants.ts
- cypress/tests/ui/folders.spec.ts
- cypress/tests/ui/home-page.spec.ts
- cypress/tests/ui/invocations.spec.ts
- package-lock.json
- package.json
- src/common/api/collections.ts
- src/common/api/teams.ts
- src/common/components/Collections/CollectionCard.tsx
- src/common/components/Folders/Folders.tsx
- src/common/components/Invocations/InvocationListItem.tsx
- src/common/types/team.ts
- src/common/types/user.ts
- src/configs/router/index.tsx
- src/pages/Collection/CollectionHome.tsx
- src/pages/home/Home.tsx
- A home page is added to view your personal account and the teams you are a member of.
- Collections can be accessed from User or Team.
- The following tests only modified so that they can be per User, there are no new tests within them.
- `collections.spec`
- `invocations.spec`
- `environments.spec`
- `folders.spec`
- `change-password.spec`
- Add a new home page
- Add access to collections by team
- Add CRUD of teams from backend
- Add tests for new home page
> Feat: Add new home page by Team or User

- package-lock.json
- package.json
- src/common/api/invocations.ts
- src/common/components/Input/ContractInput.tsx
- src/common/components/Tabs/AuthorizationTab/AuthorizationTab.tsx
- src/common/components/auth/stellar/ConnectWallet.tsx
- src/common/components/auth/stellar/ImportAccount.tsx
- src/modules/auth/context/AuthContext.tsx
- src/modules/auth/interfaces/IAuthenticationContext.ts
- src/pages/Invocation/InvocationPage.tsx
- src/pages/Invocation/useInvocation.tsx
This set of changes is dedicated to integrating the work of @silviojrcc, introducing several features and improvements to the project. The focus areas include wallet management, Stellar transaction signing, and invocation handling. Additionally, it comprises various refactors and updates to enhance code readability and functionality.
- **Feature**: Connect Wallet
- **Details**: Introduced initial support for connecting a Stellar wallet.
- **Enhancements**:
- **Details**:
- Added support for Stellar transaction signing on the Invocation Page.
- Enhanced wallet management in the authentication context.
- Integrated Wallet Connect into the Authorization Tab.
- Added Stellar Wallet Connection functionality.
- **Features**:
- **Details**:
- Added invocation preparation support in the …
> Feat / Global Authentication

- src/modules/auth/context/AuthContext.tsx
Refactor token handling and enhance error safety in `AuthContext`.
1. **Token Handling:**
- Consolidated token extraction to remove redundancy:
```typescript
const { accessToken, refreshToken } = payload;
```
- Updated token decoding to use `idToken`:
```typescript
const decodedToken = cookieService.decodeToken(idToken);
```
2. **Error Handling:**
- Simplified error description access:
```typescript
setStatusState('signIn', { error: error?.details?.description });
```
- Updated `toast` to correctly display error messages:
```typescript
toast({
title: `${error.error} - ${error.message}`,
description: error?.details?.description,
variant: 'destructive',
});
```
- **File Changed:** `src/modules/auth/context/AuthContext.tsx`
- **Lines Added:** 4
- **Lines Deleted:** 4
**File Changes:**
- …
> Refactor / Token handling and enhance error safety in auth context

- src/modules/auth/context/authContext.tsx
- src/modules/auth/interfaces/IAuthService.ts
- src/modules/auth/services/auth.service.ts
This set of commits focuses on refactoring the password handling methods within the authentication context and services. The changes streamline the password change process, improve code clarity, and remove redundant code.
1. **Update Password Change Method in Auth Context**:
- Modified the `authContext.tsx` file to streamline the password change logic.
- **Changes**:
- Removed redundant lines and improved error handling.
- The `changePassword` method now takes fewer parameters and has simplified logic.
- **File**: `src/modules/auth/context/authContext.tsx`
- **Changes**: 4 deletions, 1 addition
2. **Refactor Password-Related Methods in AuthService Interface**:
- Updated the `IAuthService` interface to reflect the changes in password handling.
- **Changes**:
- The `confirmPassword` method …
> Fix / Password Handling Issue

- src/common/components/Input/ContractInput.tsx
- src/common/components/Tabs/FunctionsTab/UploadWasmDialog.tsx
- src/modules/auth/context/authContext.tsx
- src/modules/auth/interfaces/IValidateToken.ts
- src/modules/auth/services/auth.service.ts
This update includes several improvements and new features in the authentication system. Console logging has been removed for cleaner output. Error handling and token refresh logic in the authentication context have been refactored. Additionally, an interface for token validation has been added, and token validation functionality has been integrated into the authentication service.
1. **Removed Console Logging for Cleaner Output**:
- **Files Changed**:
- `src/common/components/Input/ContractInput.tsx`
- `src/common/components/Tabs/FunctionsTab/UploadWasmDialog.tsx`
2. **Refactored Auth Context for Improved Error Handling and Token Refresh**:
- **Files Changed**:
- `src/modules/auth/context/authContext.tsx`
3. **Added Interface for Token Validation**:
- **Files Changed**:
- …
> Fix/ Auth validation refresh token

- src/pages/collection/invocationbycollection.tsx
- Renamed "Invocations" to "Collection Runner" and enhanced the UI for improved usability and consistency.
- Updated the InvocationByCollection page to replace the "Invocations" text with "Collection Runner".
- Enhanced the styling of buttons and dropdowns to improve user experience and alignment with the overall design.
- Adjusted the layout for better visual presentation, including a more prominent heading and a cleaner execution mode selector.
- Added hover and focus effects for better accessibility and responsiveness during interaction.
> Rename 'Invocations' to 'Collection Runner' and enhance UI styling

- src/pages/auth/protectedRoute.tsx
This commit enhances the session refreshing logic in a protected route component. The update ensures that the session refresh is only triggered when certain conditions related to the session status are met.
1. **Enhanced `handleRefreshSession` logic**:
- Added conditional checks on `statusState.refreshSession.status` and `statusState.refreshSession.loading` to optimize when the session refresh is triggered.
- **Files Changed**: 1
- **Lines Added**: 11
- **Lines Deleted**: 2
**File Changes:**
- `src/pages/auth/protectedRoute.tsx`: 11 additions and 2 deletions.
> Fix / Enhanced session refreshing in protected route

- src/common/components/Input/SelectInterval.tsx
This pull request includes a change to the `SelectInterval` component in the `src/common/components/Input/SelectInterval.tsx` file. The update modifies the list of available intervals for selection.
* [`src/common/components/Input/SelectInterval.tsx`](diffhunk://#diff-2cadea103e595b3e54a4d55eaa65ec72aff136e50e872ebd749d24c437d5ee90L60-R60): Expanded the list of available intervals to include more options such as 90, 120, 180, 240, and 300 minutes.
> Expands available intervals for selection
